// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Service.proto

package com.grpccrudserver.proto;

public interface OperationalStatusProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:OperationalStatusProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string operationResult = 1;</code>
   */
  String getOperationResult();
  /**
   * <code>string operationResult = 1;</code>
   */
  com.google.protobuf.ByteString
      getOperationResultBytes();

  /**
   * <code>string operationName = 2;</code>
   */
  String getOperationName();
  /**
   * <code>string operationName = 2;</code>
   */
  com.google.protobuf.ByteString
      getOperationNameBytes();
}
