// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Service.proto

package com.grpccrudserver.proto;

public final class Service {
  private Service() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UserDetailsRequestProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UserDetailsRequestProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UserRestProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UserRestProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_OperationalStatusProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_OperationalStatusProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UserRestProtoColl_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UserRestProtoColl_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UserIdProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UserIdProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UserUpdateProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UserUpdateProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UserListLimit_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UserListLimit_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\rService.proto\"_\n\027UserDetailsRequestPro" +
      "to\022\021\n\tfirstName\030\001 \001(\t\022\020\n\010lastName\030\002 \001(\t\022" +
      "\r\n\005email\030\003 \001(\t\022\020\n\010password\030\004 \001(\t\"S\n\rUser" +
      "RestProto\022\016\n\006userId\030\001 \001(\t\022\021\n\tfirstName\030\002" +
      " \001(\t\022\020\n\010lastName\030\003 \001(\t\022\r\n\005email\030\004 \001(\t\"H\n" +
      "\026OperationalStatusProto\022\027\n\017operationResu" +
      "lt\030\001 \001(\t\022\025\n\roperationName\030\002 \001(\t\"=\n\021UserR" +
      "estProtoColl\022(\n\020user_rest_protos\030\001 \003(\0132\016" +
      ".UserRestProto\"\035\n\013UserIdProto\022\016\n\006userId\030" +
      "\001 \001(\t\"_\n\017UserUpdateProto\022\016\n\006userId\030\001 \001(\t" +
      "\022<\n\032user_details_request_proto\030\002 \001(\0132\030.U" +
      "serDetailsRequestProto\",\n\rUserListLimit\022" +
      "\014\n\004page\030\001 \001(\005\022\r\n\005limit\030\002 \001(\0052\214\002\n\017grcpCru" +
      "dService\022(\n\010readUser\022\014.UserIdProto\032\016.Use" +
      "rRestProto\0226\n\ncreateUSer\022\030.UserDetailsRe" +
      "questProto\032\016.UserRestProto\022.\n\nupdateUSer" +
      "\022\020.UserUpdateProto\032\016.UserRestProto\0223\n\nde" +
      "leteUser\022\014.UserIdProto\032\027.OperationalStat" +
      "usProto\0222\n\014readListUser\022\016.UserListLimit\032" +
      "\022.UserRestProtoCollB\034\n\030com.grpccrudserve" +
      "r.protoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_UserDetailsRequestProto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_UserDetailsRequestProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UserDetailsRequestProto_descriptor,
        new String[] { "FirstName", "LastName", "Email", "Password", });
    internal_static_UserRestProto_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_UserRestProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UserRestProto_descriptor,
        new String[] { "UserId", "FirstName", "LastName", "Email", });
    internal_static_OperationalStatusProto_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_OperationalStatusProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_OperationalStatusProto_descriptor,
        new String[] { "OperationResult", "OperationName", });
    internal_static_UserRestProtoColl_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_UserRestProtoColl_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UserRestProtoColl_descriptor,
        new String[] { "UserRestProtos", });
    internal_static_UserIdProto_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_UserIdProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UserIdProto_descriptor,
        new String[] { "UserId", });
    internal_static_UserUpdateProto_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_UserUpdateProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UserUpdateProto_descriptor,
        new String[] { "UserId", "UserDetailsRequestProto", });
    internal_static_UserListLimit_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_UserListLimit_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UserListLimit_descriptor,
        new String[] { "Page", "Limit", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
