// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Service.proto

package com.grpccrudclient.proto;

public interface UserDetailsRequestProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:UserDetailsRequestProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string firstName = 1;</code>
   */
  String getFirstName();
  /**
   * <code>string firstName = 1;</code>
   */
  com.google.protobuf.ByteString
      getFirstNameBytes();

  /**
   * <code>string lastName = 2;</code>
   */
  String getLastName();
  /**
   * <code>string lastName = 2;</code>
   */
  com.google.protobuf.ByteString
      getLastNameBytes();

  /**
   * <code>string email = 3;</code>
   */
  String getEmail();
  /**
   * <code>string email = 3;</code>
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <code>string password = 4;</code>
   */
  String getPassword();
  /**
   * <code>string password = 4;</code>
   */
  com.google.protobuf.ByteString
      getPasswordBytes();
}
